language: php
php:
  - '5.5'
  - '5.6'

before_script:
  - composer install --no-interaction
  - sudo apt-get install apache2

  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
